---
version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.13"
  jobs:
    # Need the tags to calculate the version (sometimes).
    post_checkout:
      - git fetch --tags

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

sphinx:
  configuration: docs/conf.py
