---
version: 2

build:
  os: ubuntu-20.04
  tools:
    # Keep in sync with noxfile.py/tests_oldestAttrs & ci.yml/docs
    python: "3.10"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
